### ISSUE TITLE
实测linux基于debian的cutefishOS不能使用transparentcolor()方法

### ISSUE THREAD

**Issue by xiaoyy20** [Xiaokang2022/tkintertools#32]
### 🔗 Documentation Link

https://xiaokang2022.github.io/tkintertools-docs/3.0/tutorials/2-1/#213-使用部分简化的语法

### ⚡Problem

在我的linux发行版测试里，alpha方法是有效果的，但是alpha的transparentcolor()设置窗口的透明颜色不好用，抛出
_tkinter.TclError: bad attribute "-transparentcolor": must be -alpha, -topmost, -zoomed, -fullscreen, or -type
应该是没有-transparentcolor属性，这应该是底层tkinter的跨平台兼容性问题，所以不当做bug上传，只用来当作参考。

### 🚀 Suggested improvement

如果有这类扩展库的话（如果），或许可以增加一个检测系统并调用这类库，从而达到目的，当然，毕竟是tkinter本身的问题，作者做不出来也没关系，毕竟这种库相当于没有，所以这篇文章仅作参考

### ⚠️ Code of Conduct

- [x] I agree to follow this project's Code of Conduct

**Comment by xiaoyy20** [comment]
**注意，我这里提供的信息仅仅是参考用，并不是bug，因为作者在文档中提到过linux可能不适用**

**Comment by xiaoyy20** [comment]
我这里是想告诉alpha调整透明度有效，但是transparentcolor方法用不得（至少我的linux发行版是这样的）

**Comment by Xiaokang2022** [comment]
@xiaoyy20 

行，那我下次更新文档的时候顺便把这个说明写上去。

**Comment by Xiaokang2022** [comment]
@xiaoyy20 

文档站已更新：https://xiaokang2022.github.io/tkintertools-docs/3.0/tutorials/2-1/#213-%E4%BD%BF%E7%94%A8%E9%83%A8%E5%88%86%E7%AE%80%E5%8C%96%E7%9A%84%E8%AF%AD%E6%B3%95

另外教程新增标签：https://xiaokang2022.github.io/tkintertools-docs/3.0/tutorials/0-0/#11-%E6%A0%87%E7%AD%BE%E8%AF%B4%E6%98%8E

给你提到的这些内容加了“实验性”标签
