### ISSUE TITLE
关于控件自定义字体

### ISSUE THREAD

**Issue by AK16bit** [Xiaokang2022/tkintertools#45]
### Feature Description

能给指定的控件添加自定义字体吗
目前好像只能设定全局字体

### Possible Implementation

嗯。。没什么想法

### Contact Details

akpainkiller1090@gmail.com

### Code of Conduct

- [x] I agree to follow this project's Code of Conduct

**Comment by shu-shu-1** [comment]
`family`: 字体系列
`fontsize`: 字体大小
绝大部分控件都包含以上参数，详见[控件文档](https://xiaokang2022.github.io/tkintertools-docs/3.0/documents/standard/widgets/)

**Comment by Xiaokang2022** [comment]
上面的回答已经非常好了，我再补充几点。

Demo 或者示例里面不只是添加全局字体，`load_font` 的作用是将字体变得程序可用，而通过 `constants` 模块修改的是全局默认字体，所以最终表示为全局字体被修改了。但实际上，修改字体的正确操作是通过单个控件的 `family` 参数来设置，这个参数的值要求是程序可以直接使用的字体，如果系统内无法直接使用该字体，那么应该先用 `load_font` 函数导入改字体，再进行使用。

**Comment by Xiaokang2022** [comment]
如果没有任何疑问，我将在近期关闭这个 Issue

**Comment by AK16bit** [comment]
已瞭解，是我疏忽了
