### ISSUE TITLE
SegmentedButton控件设置anchor实参导致显示错误

### ISSUE THREAD

**Issue by AK16bit** [Xiaokang2022/tkintertools#46]
### Version

Latest development version

### Platform

Windows 11

### 在实例化tkintertools.SegmentedButton设置anchor实参为任意方位会导致该控件背景与按钮分离

- BUG复现示例：

![image](https://github.com/user-attachments/assets/c8bee85e-b4d6-4288-bd66-01f7ce2172b4)

- BUG复现文件：

**[bug_reproduction.py.txt (需自行更改后缀名为.py)](https://github.com/user-attachments/files/17531810/bug_reproduction.py.txt)**

### Relevant Log Output

```shell
木有，芝士渲染错误
```

### Extra Information

修复方法（未完全测试，不排除有其他BUG）：
在SegmentedButton的__init__函数中，校正ToggleButton所传入的position参数
`position = tuple(x - y for x, y in zip(position, self.offset))`

像这样：
![{E809346E-91DD-497B-822B-570DFF60FE20}](https://github.com/user-attachments/assets/6e672c00-39b6-44c7-8ee7-c58b59509df0)
![image](https://github.com/user-attachments/assets/e8e79908-5940-465e-b056-06be4242da7a)

（本来是想创个pull的，但不太会用github不会创:V）

### Contact Details

akpainkiller1090@gmail.com

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by shu-shu-1** [comment]
你可以直接在github仓库内找到文件并点击编辑，github会自动fork一份并在编辑完成后发起pull，或者，你可以手动fork一份，在自己的仓库编辑后，点击贡献，即可发起pull

**Comment by Xiaokang2022** [comment]
@AK16bit 

此问题已解决，将在下个版本发布时更新。你的解决办法是对的，期待下次贡献（先学会 PR 哈，另外，中文版贡献指南见 https://xiaokang2022.github.io/tkintertools/CONTRIBUTING/）。

**Comment by AK16bit** [comment]
好的，下次我会尝试使用pr的，感谢帮助

**Comment by Xiaokang2022** [comment]
该修复作为新版本发布，见：[`3.0.0rc4`](https://github.com/Xiaokang2022/tkintertools/releases/tag/3.0.0rc4)
